extends RefCounted
# Culture rosters (docs/v1-content.md §1; data/rosters.json; units generated by
# scripts/gen_rosters.gd). A faction with a culture recruits its culture's units, each from the
# buildings its slot needs (unlock_rules); levy units come only from calling the banners
# (core/hosts.gd). Factions without a culture (the test map) keep the generic units.

const UnitTypes = preload("res://core/unit_types.gd")
const DATA = "res://data/rosters.json"

static var _data = null
static var _by_culture = {}

static func data() -> Dictionary:
 if _data == null: _data = JSON.parse_string(FileAccess.get_file_as_string(DATA))
 return _data

# Maps that play with the culture rosters (data/rosters.json "maps": Varos); the test map keeps the
# generic units its tests are written against.
static func has_roster(culture: String) -> bool:
 return data().cultures.has(culture) and load("res://core/map_registry.gd").active in data().get("maps",[])

# The culture's unit ids, lowest tier first.
static func units_of(culture: String) -> Array:
 if not has_roster(culture): return []
 if not _by_culture.has(culture):
  var out = []
  for e in data().cultures[culture].units: out.append("%s_%s" % [culture,str(e[0])])
  out = out.filter(func(id): return UnitTypes.all().has(id))
  out.sort_custom(func(a,b): return int(UnitTypes.get_type(a).tier)<int(UnitTypes.get_type(b).tier) or (int(UnitTypes.get_type(a).tier) == int(UnitTypes.get_type(b).tier) and a<b))
  _by_culture[culture] = out
 return _by_culture[culture]

static func levy_of(culture: String) -> String:
 for id in units_of(culture):
  if bool(UnitTypes.get_type(id).get("levy",false)): return id
 return "peasant_levy"

# The culture's unit for a generic starting unit (data/rosters.json equivalents): the lowest tier of
# the same role. Unchanged without a roster.
static func equivalent(generic: String,culture: String) -> String:
 if not has_roster(culture): return generic
 var roles = data().equivalents.get(generic,[])
 if roles.is_empty(): return generic
 # The lowest tier among the listed roles (a culture without light horse uses its lightest cavalry).
 var best = ""
 for id in units_of(culture):
  if not str(UnitTypes.get_type(id).role) in roles: continue
  if best == "" or int(UnitTypes.get_type(id).tier)<int(UnitTypes.get_type(best).tier): best = id
 if best != "": return best
 # No unit of that role: the closest by category.
 var cat = str(UnitTypes.get_type(generic).category)
 for id in units_of(culture):
  if str(UnitTypes.get_type(id).category) == cat and not bool(UnitTypes.get_type(id).get("levy",false)): return id
 return generic

# The culture units a settlement's buildings unlock (unlock_rules by slot).
static func unlocks(levels: Dictionary,settlement_level: int,culture: String) -> Array:
 var out = []
 var rules = data().unlock_rules
 for id in units_of(culture):
  var rule = rules.get(str(UnitTypes.get_type(id).slot),{"never":true})
  if bool(rule.get("never",false)): continue
  var ok = true
  for k in rule:
   if k == "level":
    if settlement_level<int(rule.level): ok = false
   elif int(levels.get(k,0))<int(rule[k]): ok = false
  if ok: out.append(id)
 return out

static func reset():
 _data = null
 _by_culture = {}
