extends SceneTree
# Build a map's outputs (docs/map-pipeline-design.md §4).
#   runtime\Godot.exe --headless --path . -s scripts/build_map.gd -- --map=<map_id>
# Synthetic maps (map.json "kind": "synthetic") are generated by map/synthetic.gd; authored maps
# ("kind": "pipeline": sketch.svg + world.json) by map/pipeline.gd, then checked by map/validator.gd. Prints counts and
# the time of every step; exits non-zero on failure.

const MapRegistry = preload("res://core/map_registry.gd")

func _initialize():
 var map_id = ""
 for a in OS.get_cmdline_user_args():
  if a.begins_with("--map="): map_id = a.get_slice("=",1)
 if map_id == "" or not map_id in MapRegistry.maps():
  printerr("Usage: -s scripts/build_map.gd -- --map=<map_id>  (maps: %s)" % ", ".join(MapRegistry.maps()))
  quit(2)
  return
 var kind = str(MapRegistry.meta(map_id).get("kind",""))
 var r = {}
 match kind:
  "synthetic": r = load("res://map/synthetic.gd").build(map_id)
  "pipeline":
   r = load("res://map/pipeline.gd").build(map_id)
   if r.errors.is_empty():
    var v = load("res://map/validator.gd").validate(map_id)
    r.validation = {"errors":v.errors,"warnings":v.warnings,"skipped":v.skipped}
    for p in v.problems: print("VALIDATE %s %s: %s" % [p.level,p.check,p.message])
    if v.errors>0: r.errors.append("%d validation errors" % v.errors)
  _:
   printerr("Map %s has kind '%s': no builder for it yet." % [map_id,kind])
   quit(2)
   return
 print("BUILD_MAP %s %s" % [map_id,JSON.stringify(r)])
 quit(1 if not r.get("errors",[]).is_empty() else 0)
