extends SceneTree
# Writes the culture units (data/units/<culture>_<id>.json) from data/rosters.json, the single source
# of the V1 rosters (docs/v1-content.md §1). Run after editing the rosters:
#   runtime\Godot.exe --headless --path . -s scripts/gen_rosters.gd
# Stats grow with tier (stat_per_tier); the look is the role's template unit (data/units/<template>.json)
# tinted per culture; cost, upkeep and turns come from the tier and the role.

const UNIT_DIR = "res://data/units/"

func _initialize():
 var r = JSON.parse_string(FileAccess.get_file_as_string("res://data/rosters.json"))
 var written = 0
 for cul in r.cultures:
  var c = r.cultures[cul]
  for e in c.units:
   var u = make_unit(r,cul,c,e)
   var f = FileAccess.open(UNIT_DIR+u.id+".json",FileAccess.WRITE)
   f.store_string(JSON.stringify(u,"  ",false)+"\n")
   f.close()
   written += 1
 print("ROSTERS written %d units" % written)
 quit()

static func make_unit(r: Dictionary,cul: String,c: Dictionary,e: Array) -> Dictionary:
 var id = str(e[0])
 var tier = int(e[2])
 var role = str(e[3])
 var rd = r.roles[role]
 var tpl = JSON.parse_string(FileAccess.get_file_as_string(UNIT_DIR+str(rd.template)+".json"))
 var b = rd.battle.duplicate(true)
 var spt = r.stat_per_tier
 var k = tier-1
 for s in ["melee_attack","melee_defence","armour","morale","charge"]: b[s] = int(b[s])+int(spt[s])*k
 b.armour = mini(int(b.armour),95)
 if b.missile != null: b.missile.damage = int(b.missile.damage)+int(spt.missile_damage)*k
 var cost = int(round(float(r.cost_by_tier[k])*float(rd.cost)/10.0))*10
 var vc = tpl.get("visual_config",{}).duplicate(true)
 vc.tint = str(c.tint)
 if rd.has("scale"): vc.scale = float(rd.scale)
 var slot_kind = str(rd.slot)
 var slot = str(r.slots[slot_kind][k])
 var notes = str(e[4]) if e.size()>4 else ""
 return {
  "_note":"GENERATED by scripts/gen_rosters.gd from data/rosters.json (docs/v1-content.md §1); edit the rosters, not this file. PLACEHOLDER stats.",
  "id":"%s_%s" % [cul,id],"display_name":str(e[1]),"category":str(rd.category),"culture":cul,"tier":tier,"role":role,"slot":slot,"levy":role == "levy",
  "description":(notes+". " if notes != "" else "")+"Tier %d %s of the %s roster." % [tier,role.replace("_"," "),cul.replace("_"," ").capitalize()],
  "visual":tpl.visual,"outfit":tpl.outfit,"loadout":tpl.loadout,"visual_config":vc,
  "size":int(rd.size),"recruitment":{"cost":cost,"turns":int(r.turns_by_tier[k])},
  "card_portrait":tpl.card_portrait,"battle":b,
  "placeholder_stats":{"_note":"PLACEHOLDER values (generated from data/rosters.json); upkeep feeds the economy.","upkeep":int(round(cost*float(r.upkeep_share)))}}
